name: Update ARS data
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.7

      - name: Install Python dependencies
        run: poetry install
        
      - name: Download ARS list
        run: poetry run python ars.py

      - name: Update git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update ARS lists"
          file_pattern: 'data'
